#!groovy

// Generated by IBM TransformationAdvisor
// Thu Nov 01 20:07:56 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}