#!groovy

// Generated by IBM TransformationAdvisor
// Mon Oct 15 19:12:15 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}